### ISSUE TITLE
Discord Pulls every 30sec 

### ISSUE THREAD

**Issue by zuiji** [warlof/seat-discord-connector#12]
i think you missed a / at *,30***

so youtry pull every 30 sec instead of every 30 min :D 

![sceduled commands](https://user-images.githubusercontent.com/32148833/41936632-19f2defa-798e-11e8-90c4-abca674ef76e.PNG)

**Comment by tarioch** [comment]
it's *,30 not of 0,30, so I think this is a bug?

**Comment by warlof** [comment]
has been addressed in 3.1.1
