### ISSUE TITLE
role update not updating users

### ISSUE THREAD

**Issue by BrownStar** [warlof/seat-discord-connector#16]
I have quite a few users that have registered successfully using the discord-connector, yet when I look in 'user mapping' they show no roles. I removed all other filters except for corp level and it still does not update users.

I have run the policy update on a 5 min cron and manually  through artisan with no luck. I am not sure if there is a log that I can view to provide more detail.

mapping always shows: https://i.imgur.com/jCzhYKF.png

**Comment by warlof** [comment]
What do you have in job result ?

Also, discord api is call limited, and running policy every 5 minutes could lead to a bot ban. You should reduce it's frequency.

Default is every 30min.

---

Does your users have all attached refresh token valid ? (go in Settings > Users and track for red cross).

**Comment by BrownStar** [comment]
The job in horizon is showing success, is there other place to look?

discord api is not banned (yet) I manually updated user in discord with roles, 5mins later roles removed via bot. I will change to 30mins though as that is more practical timing.

User refresh token is valid and i have ran esi:update:characters for the character in question.

**Comment by BrownStar** [comment]
User does have 1 character in group that has an invalid token. 1 character out of 30, does it reject on only 1 invalid token in group?

**Comment by BrownStar** [comment]
looks like if you do have 1 invalid token, it sets the user to not valid

**Comment by draymah** [comment]
GuzzleHttp\Exception\ClientException: Client error: `PATCH https://discordapp.com/api/v6/guilds/162614064906764288/members/215269595961884674` resulted in a `403 FORBIDDEN` response: < getting a few of these in the Warlof\Seat\Connector\Discord\Jobs\MemberOrchestrator job
