### ISSUE TITLE
403 Errors

### ISSUE THREAD

**Issue by solamance** [warlof/seat-discord-connector#2]
Hey! I'm not sure if I did something wrong, or if I'm missing a step - but following the integration, I'm getting 403 errors in my Laravel. 

Any insight?

GuzzleHttp\Exception\ClientException: Client error: `PATCH https://discordapp.com/api/v6/guilds/<redacted>/members/<redacted>` resulted in a `403 FORBIDDEN` response:

**Comment by warlof** [comment]
Hello,

Where did you get that message?

**Comment by solamance** [comment]
Hey! 

I pulled up the failed jobs section of my SeAT instance, and opened the MemberOrchestrator job that had failed. 

Once I open that, it gives me job ID, queue, tags, failed date/time. Then the error code above, followed by a stack trace and then a Data section.

**Comment by warlof** [comment]
@solamance ensure the bots role is at top position of roles.

**Comment by warlof** [comment]
@solamance any news about this ?
