### ISSUE TITLE
Logs giving very limited information

### ISSUE THREAD

**Issue by kwazulueve** [warlof/seat-discord-connector#20]
Currently I only see the following log messages 

![image](https://user-images.githubusercontent.com/25641678/44369080-62f4cd80-a4d5-11e8-8e6e-bdda1755f24a.png)

Based on the description I would expect to see also join/leave changes for channels (we combined Seat Groups with opt-in channels for Discord) and have the messages contain which user is affected. Not sure if that was intended or is supposed to work like that

**Comment by dstevens79** [comment]
bump
