### ISSUE TITLE
Afraid I still get a lot of "429 TOO MANY REQUESTS" errors

### ISSUE THREAD

**Issue by geedon** [warlof/seat-discord-connector#24]
Hi, I prevously reported this problem and it has been much better since I last patched but I still get a lot of the following with my 250 man corp when the connector cron job runs...

>[2018-10-11 16:03:04] local.ERROR: There was an error executing the modifyGuildMember command: Client error: `PATCH https://discordapp.com/api/v6/guilds/210370667353210881/members/210401320203583481` resulted in a `429 TOO MANY REQUESTS` response:
 {"exception":"[object] (GuzzleHttp\\Command\\Exception\\CommandClientException(code: 0): There was an error executing the modifyGuildMember command: Client error: `PATCH https://discordapp.com/api/v6/guilds/210370667353210881/members/21040132020358348$
 at /var/www/html/eveseat/vendor/guzzlehttp/command/src/Exception/CommandException.php:57, GuzzleHttp\\Exception\\ClientException(code: 429): Client error: `PATCH https://discordapp.com/api/v6/guilds/210370667353210881/members/210401320203583481` resul$
 at /var/www/html/eveseat/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)

**Comment by geedon** [comment]
Hi, thanks for getting back to me. The discord connector runs on a 1 hour cron cycle.

**Comment by Maldaris** [comment]
We're encountering this same issue, however these failed GuzzleHTTP requests don't persist to the Horizon dashboard. (It instead reports a too many retries/timeout for the job).

Also failed requests don't display any of the ratelimit headers described [here](https://discordapp.com/developers/docs/topics/rate-limits#header-format-rate-limit-header-examples), which makes debugging nearly impossible.

**Comment by mckernanin** [comment]
I'm getting this as well, with the cron scheduled at 1h and only 2 characters authed

**Comment by mckernanin** [comment]
With only 2 characters added, I'm seeing a spike of 67 calls when the cron runs 😬 
<img width="952" alt="Screenshot 2019-03-15 09 40 08" src="https://user-images.githubusercontent.com/6300047/54443831-1853d080-4707-11e9-9730-d2d8f1be42fb.png">

**Comment by Pr3ciseD34th** [comment]
Im having the same issue with this

**Comment by mckernanin** [comment]
My issue was caused by the discord bot not being at the top of the role list. When I tried adding a user who did not have our Admin role, I got added successfully. When I tried to add that role via the bot, I got the errors again. It does seem less than optimal that this plugin keeps trying to blast the discord API when it gets a 403 error.

**Comment by warlof** [comment]
@mckernanin how many roles do you have on that discord?

**Comment by mckernanin** [comment]
~10? I messaged you on slack earlier, and posted this after I got out discord working.

**Comment by dougestey** [comment]
Oddly, I'm now running into this again on a Discord with only 8 roles / 13 users. Cron set to 1 hour. And here's the kicker - it only fails for one user in the sync run, consistently. Maybe the 429 is a red herring?

**Comment by vitaliusdfox** [comment]
Hi there. Same problem here.
Everything works fine till 30.04.2019. Discord-connector goes silent and stop granting any roles. Took me some time to notice it.
Few days ago I removed all discord jobs from cron and today was a day when discord-connector didn't try break a invisible 429 wall. So logs was crystal clear and I decided to retry one failed job for one special person.
And here what I got:
http://freetexthost.com/1w4143vim3 
First 10 tries was with 400 (BAD REQUEST) response and changed to 429.

So, even with one job with one person you can get this error. Thats means I'm not a spam discord server with huge amount of requests.

Any idea what cause it?

618 ppl on my server (300~ should be with roles)
47 roles (44 of them was used by discord-connector correctly till 30.04.2019 )

**Comment by Eingang** [comment]
Ditto here on the 400s followed by 429s for the two new people who should have been granted roles since April 30th. April 29th worked fine. The two people after that are broken. Did Discord change something on their end in the API maybe? Is there something we can enable to log the JSON container?

**Comment by warlof** [comment]
Hi,

The 400 is a know issue.
Thanks to discord team who push breaking changes on their latest live api.

However, it has break restcord library which is used to talk with Discord. 
There is some patch which can be apply manually for now https://github.com/restcord/restcord/issues/83

**Comment by kwazulueve** [comment]
Manual fix worked here, thanks a lot!

**Comment by dstevens79** [comment]
manual fix this the easy way 👍
sudo nano /var/www/seat/vendor/restcord/restcord/src/Resources/service_description-v6.json
delete lines 459 & 468
this worked for me on 6-30-19
