### ISSUE TITLE
Already have a Discord API Access Setup? Can't Pull Roles.

### ISSUE THREAD

**Issue by MokeyII** [warlof/seat-discord-connector#25]
It appears you already have a Discord API access setup. In order to prevent any mistakes, Client ID and Client Secret fields have been disabled. Please use the rubber in order to enable modifications.

I'm not sure why this is happening. But I've tried recreating the bot multiple times and I get the same result. I cannot pull roles to allow this to work.

I've tried implementing this on a fresh discord server and the issue persists through.

**Comment by warlof** [comment]
This message is a disclaimer only. Not an error.

**Comment by dstevens79** [comment]
i actually have this error too
i can establish a connection to discord with seat bot but then i cannot pull roles, says script ran successfully but i get no results actually seeded back into seat from discord?
