### ISSUE TITLE
Bot Not Connecting

### ISSUE THREAD

**Issue by Code2200** [warlof/seat-discord-connector#29]
I recently just setup SEAT for my corp and installed the Discord Connector addon. I went through the setup guide, but I can't get the connector to update and take my to bot to select a server. I enter the Discord Client ID, Secret, and Bot Token -> click "Update" and it takes me to a black screen that says "Unknown_Error You may now close this window or tab."

Did I miss something?

**Comment by herpaderpaldent** [comment]
You probaly havent provided the callback url to your discord application oAuth

**Comment by Code2200** [comment]
The instructions had me do two redirects:
1. for the oauth
2. for the server

Both were updated to use my SEAT's web address.  There is a second box below that called 'OAuth2 URL Generator' which has a drop down to select one of the two callbacks. I have tried both, but neither seems to change any of the IDs.

**Comment by Code2200** [comment]
Restarted SEAT server deleted the bot and remade.
