### ISSUE TITLE
DataTables warning when opening user mapping

### ISSUE THREAD

**Issue by StarSyth** [warlof/seat-discord-connector#32]
DataTables warning: table id=users-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by Fundaris** [comment]
Hey since this error can have multiple reasons could you check your network tab for HTTP error code from the ajax and also into the laravel.log,

Also does it take for ever to load or does this error comes instantly?

**Comment by StarSyth** [comment]
It pops up instantly, also pops up on the log section too
![image](https://user-images.githubusercontent.com/37351296/52880286-78337780-3159-11e9-894d-27fcad0470c7.png)

**Comment by warlof** [comment]
Hi @StarSyth,

Did you run migrations ?

**Comment by StarSyth** [comment]
ran migration again to make sure, "Nothing to migrate".

**Comment by warlof** [comment]
Do you have any log for me?

**Comment by entropylaw** [comment]
I'm having the same problem. Getting this.

`[2019-07-13 21:55:57] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggrega                                                      te from (select '1' as `row_count` from `warlof_discord_connector_users` left join `user_settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `use                                                      r_settings`.`name` = main_character_id left join `character_infos` on `character_id` = `value` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %s% or LOWER(`warlof_disc                                                      ord_connector_users`.`user_name`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`discord_id`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %s% or LOWER(`warlof                                                      _discord_connector_users`.``) LIKE %s%)) count_row_table) {"userId":91622612,"exception":"[object] (Yajra\\DataTables\\Exceptions\\Exception(code: 0): SQLSTATE[42S22]: Column not foun                                                      d: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `warlof_discord_connector_u                                                      sers` left join `user_settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `user_settings`.`name` = main_character_id left join `character_infos`                                                       on `character_id` = `value` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`user_name`) LIKE %s% or LOWER(`warlof_discord                                                      _connector_users`.`discord_id`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %s% or LOWER(`warlof_discord_connector_users`.``) LIKE %s%)) count_row_table) at /var/w                                                      ww/seat/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php:778, Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column                                                       'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `warlof_discord_connector_users` left join `user_                                                      settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `user_settings`.`name` = main_character_id left join `character_infos` on `character_id` = `v                                                      alue` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`user_name`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`dis                                                      cord_id`) LIKE %s% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %s% or LOWER(`warlof_discord_connector_users`.``) LIKE %s%)) count_row_table) at /var/www/seat/vendor/laravel                                                      /framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connec                                                      tor_users.user_name' in 'where clause' at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: 42S22): SQLSTATE[42S22]: Column not foun                                                      d: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)
[stacktrace]
#0 /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php(106): Yajra\\DataTables\\DataTableAbstract->errorResponse(Object(Illuminate\\Database\\QueryException))
#1 /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/DiscordController.php(107): Yajra\\DataTables\\QueryDataTable->make(true)
#2 [internal function]: Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\DiscordController->getUsersData()
#3 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('getUsersData', Array)
#5 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Warlof\                                                      \Seat\\Connector\\Discord\\Http\\Controllers\\DiscordController), 'getUsersData')
#6 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#7 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#8 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Bouncer/Bouncer.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Bouncer\\Bouncer->handle(Object(Illuminate\\Http\\Request), Object(C                                                      losure), 'discord-connect...')
#11 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Locale.php(44): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#13 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Locale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#14 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/seat/vendor/eveseat/web/src/Http/Middleware/Authenticate.php(67): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Seat\\Web\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closu                                                      re))
#17 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminat                                                      e\\Http\\Request))
#19 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Ob                                                      ject(Closure))
#20 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(68): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illu                                                      minate\\Http\\Request))
#22 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Reques                                                      t), Object(Closure))
#23 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/seat/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illumina                                                      te\\Http\\Request))
#25 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), O                                                      bject(Closure))
#26 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/seat/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Htt                                                      p\\Request))
#28 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(C                                                      losure))
#29 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Il                                                      luminate\\Http\\Request))
#31 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Reque                                                      st), Object(Closure))
#32 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/seat/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Ht                                                      tp\\Request))
#34 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(                                                      Closure))
#35 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illumina                                                      te\\Http\\Request))
#39 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\                                                      \Route))
#40 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#41 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#42 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Ht                                                      tp\\Request))
#43 /var/www/seat/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Il                                                      luminate\\Http\\Request))
#47 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Requ                                                      est), Object(Closure))
#48 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Il                                                      luminate\\Http\\Request))
#50 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Requ                                                      est), Object(Closure))
#51 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Ill                                                      uminate\\Http\\Request))
#53 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Reque                                                      st), Object(Closure))
#54 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Obj                                                      ect(Illuminate\\Http\\Request))
#56 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http                                                      \\Request), Object(Closure))
#57 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/www/seat/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#60 /var/www/seat/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Requ                                                      est))
#61 /var/www/seat/public/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#62 {main}
"}
`

**Comment by flyingferret** [comment]
Also getting an AJAX error on the User Mapping page 

> [2019-07-14 00:10:28] local.ERROR: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `warlof_discord_connector_users` left join `user_settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `user_settings`.`name` = main_character_id left join `character_infos` on `character_id` = `value` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`user_name`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`discord_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %l% or LOWER(`warlof_discord_connector_users`.``) LIKE %l%)) count_row_table) {"userId":91089388,"exception":"[object] (Yajra\\DataTables\\Exceptions\\Exception(code: 0): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `warlof_discord_connector_users` left join `user_settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `user_settings`.`name` = main_character_id left join `character_infos` on `character_id` = `value` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`user_name`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`discord_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %l% or LOWER(`warlof_discord_connector_users`.``) LIKE %l%)) count_row_table) at /var/www/seat/vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php:778, Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as `row_count` from `warlof_discord_connector_users` left join `user_settings` on `warlof_discord_connector_users`.`group_id` = `user_settings`.`group_id` and `user_settings`.`name` = main_character_id left join `character_infos` on `character_id` = `value` where (LOWER(`warlof_discord_connector_users`.`group_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`user_name`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`discord_id`) LIKE %l% or LOWER(`warlof_discord_connector_users`.`nick`) LIKE %l% or LOWER(`warlof_discord_connector_users`.``) LIKE %l%)) count_row_table) at /var/www/seat/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63, PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'warlof_discord_connector_users.user_name' in 'where clause' at /var/www/seat/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61)

**Comment by warlof** [comment]
Hi @entropylaw @flyingferret 

What are you exactly doing ?
Just showing  `User Mapping` page does not return any error with latest 3.3.2.

Are you trying to sort a column or search something ?!

**Comment by flyingferret** [comment]
Typing into the search bar

**Comment by warlof** [comment]
So you should be ok if you're updating :)

**Comment by entropylaw** [comment]
`An error occurred while exchanging credentials with Discord. SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '128497971103924224' for key 'discord_users_discord_id_unique'`

One of my members is getting this error when trying to join discord.

**Comment by flyingferret** [comment]
Thanks will update when I get home
