### ISSUE TITLE
Access Management not working

### ISSUE THREAD

**Issue by JacobOkanta** [warlof/seat-discord-connector#33]
I have had the connector installed on my SeAT instance for some time now however it has somewhat recently stopped working, I attempted to open the access management page and was presented with this error https://pastebin.com/fZSTaYzN this is with debug mode on. Nothing has changed on my server to my knowledge. I am running SeAT through Docker. I believe this happened shortly after an update to SeAT and likely also the plugin, but I am not certain.

**Comment by warlof** [comment]
@jacobokanta did you drop a group from the linked Discord or maybe a corporation from SeAT?

**Comment by JacobOkanta** [comment]
I don't believe any corporations were dropped but some roles may have been removed.

**Comment by warlof** [comment]
Just for some confirmation, can you execute the following SQL query?

```
SELECT COUNT(*)
FROM warlof_discord_connector_roles
WHERE warlof_discord_connector_roles.id NOT IN (SELECT discord_role_id FROM
warlof_discord_connector_role_corporations);
```

**Comment by JacobOkanta** [comment]
This was the output.
`+----------+
| COUNT(*) |
+----------+
|        0 |
+----------+
1 row in set (0.001 sec)`

**Comment by warlof** [comment]
Well, let's check the other side

```
SELECT COUNT(*)
FROM warlof_discord_connector_role_corporations
WHERE corporation_id NOT IN (SELECT corporation_id FROM
corporation_infos);
```

**Comment by JacobOkanta** [comment]
Output of that was
`+----------+
| COUNT(*) |
+----------+
|        2 |
+----------+
1 row in set (0.001 sec)`

**Comment by warlof** [comment]
Seems that you have a dropped corporation with an existing reference. This is causing yore trouble.

The quicker fix I can offer you is to run the query bellow. 

```
DELETE
FROM warlof_discord_connector_role_corporations
WHERE corporation_id NOT IN (SELECT corporation_id FROM
corporation_infos);
```

**Comment by JacobOkanta** [comment]
That seems to have fixed the issue. Thank You!
