### ISSUE TITLE
Bot is showing as offline and is failing to show roles

### ISSUE THREAD

**Issue by samsoliman** [warlof/seat-discord-connector#35]
After installing discord connector, looks like the bot shows as offline when joins the server I did move the role at the top already. Also, it fails to pull the server roles when I click the update role button on Seat and it says job successful. 

Not sure what am I doing wrong here, Help?

**Comment by samsoliman** [comment]
Update:
The bot managed to sync the Discord server roles with Seat however it is still showing as offline in the member list. Any idea why is that happening and how can I get it to show online?

**Comment by warlof** [comment]
The connector is using bot access since it's the only way to manage users in a guild.

But it's not a bot - which is the reason why it's showing offline.

**Comment by samsoliman** [comment]
Is there a way I can modify it into a bot?

**Comment by warlof** [comment]
Sure, contribute to this repository. Even if I don't see the need.
