### ISSUE TITLE
Not an issue just a question. 

### ISSUE THREAD

**Issue by ssotirov01** [warlof/seat-discord-connector#38]
Hi There,

How do you install discord connector if the SeAT is installed via Docker installation method?

Best Regards

**Comment by herpaderpaldent** [comment]
You'll find your answer in our official documentation: https://eveseat.github.io/docs/admin_guides/docker_admin/#installing-plugins

**Comment by ssotirov01** [comment]
Sorry for the stupid question, but in this case how should I edit the .env

Is the below correct?

# SeAT Plugins
# This is a list of the all of the third party plugins that you
# would like to install as part of SeAT. Package names should be
# comma separated if multiple packages should be installed.
SEAT_PLUGINS=warlof/seat-discord-connector

**Comment by herpaderpaldent** [comment]
you need to update seat: https://eveseat.github.io/docs/admin_guides/docker_admin/#performing-updates

**Comment by ssotirov01** [comment]
@herpaderpaldent Thank  you very much for your help. I've managed to install discord connector. It is shown now in SeAT.  I successfully connect to discord with Client ID,  Client Secret and Bot Token
 
When I click on join server this is the error I get:
An error occurred while exchanging credentials with Discord. SQLSTATE[42S02]: Base table or view not found: 1146 Table 'seat.warlof_discord_connector_users' doesn't exist (SQL: select * from `warlof_discord_connector_users` where (`group_id` = 1) limit 1)
:
When I click on "Access Management" I get error message : "Whoops, looks like something went wrong."

**Comment by herpaderpaldent** [comment]
maybe it's better to join us on slack to ask these kind of questions: https://eveseat-slack.herokuapp.com/ 

You need to run migrations: `docker-compose exec seat-app php artisan migrate` 

for more support join our slack in channel plugins
