### ISSUE TITLE
Slow invitation and role granting  while heavy server load 

### ISSUE THREAD

**Issue by JHXSMatthew** [warlof/seat-discord-connector#39]
Hi,
I've been playing around with discord connector. This is an awesome plugin and thank you so much for open source and effort.

I have experienced a huge delay if one attempts to connect to discord when the SEAT workers are working on fetching char/corp info from ESI,  

This is a very common case when new bro joins corp and joined discord but have to wait there for a long time. 

This happens because seat dispatches jobs to fetch data from ESI before the user interacts with the web UI to connect its seat account to discord. Another plugin, seat group solves this by dispatching sync jobs to the "high" queue which has higher priority than default queue. 

I submitted a PR includes changes. It is very simple but I believe it will improve user experiences in the scenario described above
.

**Comment by warlof** [comment]
Affaict there is not a queue with higher priority than another one. It's only some user friendly naming 😉
But I can understand the request.
