### ISSUE TITLE
3.2 minimum required version error 

### ISSUE THREAD

**Issue by JHXSMatthew** [warlof/seat-discord-connector#45]
Hi,

Today I restarted my seat instance in docker and it stucks at the starting phase. 

What I found: 
1. The minimum requirement is alpha if installed seat on docker following official installing guide. 
dev-develop level will make seat-app restarts forever because composer refuse to install it and exit on error. 

2. Php composer will use 3.2 as default version which trigger this issue.

**Comment by warlof** [comment]
unfortunately, the current restcord stable version isn't working with last introduced Discord API changes - I can only use the one on develop branch :/

Did you try to require 3.1.* ? since docker is using the plugins variable as a composer parameter, I think it can work (`warlof/seat-discord-connector:^3.1`)

**Comment by entropylaw** [comment]
You can just add this to your .env
SEAT_PLUGINS=warlof/seat-discord-connector,restcord/restcord:dev-develop

Works just fine.

**Comment by Geabo** [comment]
> You can just add this to your .env
> `SEAT_PLUGINS=warlof/seat-discord-connector,restcord/restcord:dev-develop`
> 
> Works just fine.

@warlof is there a better fix for running on a docker install?

This is causing infinite restarts on a fresh install. I have a separate non-docker install where the edit to `composer.json` works great - is there anyway to to accomplish this in the docker install?

**Comment by dstevens79** [comment]
i had a similar issue and i removed restcord and reran my SDC installer as sudo 
this fixed the issue for me, but now i have a 429 too many requests :(

**Comment by warlof** [comment]
@dstevens79 you got 429 on 3.2 Gen?
