### ISSUE TITLE
[Feature Request] Discord connect menu option doesn't respect the view permission

### ISSUE THREAD

**Issue by mmolitor87** [warlof/seat-discord-connector#5]
Pretty much what the title says, but everyone can see the discord connect menu option without having the DiscordConnectorView permission.

**Comment by warlof** [comment]
The join option is available for all by design. This permission is granting view access to the ACL.

**Comment by mmolitor87** [comment]
It would be really nice to have a view permission to prevent randoms from joining discord after registering with a random alpha alt, similar to how seat-groups does this.
