### ISSUE TITLE
seat-discord-connector not updating

### ISSUE THREAD

**Issue by Geabo** [warlof/seat-discord-connector#51]
Not sure what I'm missing, but this plugin is not updating from 3.1.6 to 3.2.1. I've tried a few different update commands, but I thought that seat updates all of its plugins when updating. (seat-groups did update automatically).

How do I update just the discord-connector plugin?

Thanks.

**Comment by warlof** [comment]
Hi @Geabo , I'm redirecting you to #45 which contain information about this.
