### ISSUE TITLE
Warlof\Seat\Connector\Discord\Jobs\SyncRole Fails with No Error Message

### ISSUE THREAD

**Issue by tohuw** [warlof/seat-discord-connector#56]
When I select to sync roles, it always fails. I see no error in the logs section or in Horizon. Using latest version (installed today). The bot is in the server, and all the authorization parts appeared to work fine.

**Comment by warlof** [comment]
Sync roles is only pulling roles from Discord to your SeAT instance.
If it's failing, you should have at least informations into `laravel.log` file

**Comment by tohuw** [comment]
Ah right. Here's something relevant, I think:

`laravel-2019-07-08.log:[2019-07-08 01:33:41] local.ERROR: Type error: Argument 1 passed to Warlof\Seat\Connector\Discord\Http\Controllers\Services\ServerController::exchangingToken() must be of the type string, null given, called in /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php on line 79 {"userId":95214766,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\Services\\ServerController::exchangingToken() must be of the type string, null given, called in /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php on line 79 at /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php:126)`

**Comment by tohuw** [comment]
Also, in case it helps:

```
| Vendor  | Package Name           | Installed Version |
| ------- | ---------------------- | ----------------- |
| eveseat | api                    | 3.0.7             |
| eveseat | console                | 3.0.5             |
| eveseat | eveapi                 | 3.0.15            |
| eveseat | notifications          | 3.0.5             |
| eveseat | services               | 3.0.8             |
| eveseat | web                    | 3.0.21            |
| warlof  | seat-discord-connector | 3.3.1             |
```

And here's the entire output of `grep -i warlof storage/logs/laravel-2019-07-0*`

```
storage/logs/laravel-2019-07-08.log:[2019-07-08 01:33:41] local.ERROR: Type error: Argument 1 passed to Warlof\Seat\Connector\Discord\Http\Controllers\Services\ServerController::exchangingToken() must be of the type string, null given, called in /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php on line 79 {"userId":95214766,"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\Services\\ServerController::exchangingToken() must be of the type string, null given, called in /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php on line 79 at /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php:126)
storage/logs/laravel-2019-07-08.log:#0 /var/www/seat/vendor/warlof/seat-discord-connector/src/Http/Controllers/Services/ServerController.php(79): Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\Services\\ServerController->exchangingToken(NULL)
storage/logs/laravel-2019-07-08.log:#1 [internal function]: Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\Services\\ServerController->callback()
storage/logs/laravel-2019-07-08.log:#4 /var/www/seat/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Warlof\\Seat\\Connector\\Discord\\Http\\Controllers\\Services\\ServerController), 'callback')
```

**Comment by tohuw** [comment]
I just noticed something odd: when the job fails, the "Failed At" time is always "69-12-31 18:00:00". However, other (non SDS) jobs that fail don't report this erroneous time.

**Comment by warlof** [comment]
The upper error doesn't look like to be related to your job issue but more to someone who cancel the binding process of its account - (mostly, he will not get access to Discord).

How long the job is running and how many roles/user do you have on your Discord ?!

**Comment by tohuw** [comment]
Ah, gotcha.

The job only runs for ~5 seconds. I have 75 users and 30 roles.

**Comment by tohuw** [comment]
I should note it also only runs for ~5 seconds on a test server with 2 users and 1 role...

**Comment by tohuw** [comment]
Not sure if this is interesting, but here's the data from the failed attempt:

```
{
  "tags": [
    "sync",
    "conversations"
  ],
  "tries": 1,
  "job": null,
  "connection": null,
  "queue": null,
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

**Comment by tohuw** [comment]
Ah, I found it @warlof. Really sorry, but it's from my attempt to multi-instance SeAT (providing another instance of SeAT to a different corp). That's my fault. Once I shut down that second instance, everything worked as expected. Apologies!

**Comment by warlof** [comment]
Don't worry, it's ok :)

For information, I just merged some PR in Core yesterday which allow to tweak the used Redis database.

That's probably what was causing you troubles since each of your instance where sharing the exact same database :p (some, same cache and same queue)

**Comment by tohuw** [comment]
Ah, that's interesting to me! So you think if I manually changed that value in my second instance to some arbitrary name, this problem wouldn't occur?

**Comment by tohuw** [comment]
Oh wait, just do your change and set Redis_database in .env, duh. So just give it any name, doesn't matter?

**Comment by warlof** [comment]
Not name but number - Redis is using index.
But that's it.

**Comment by tohuw** [comment]
Thanks, it works well. That's an awesome fix! Much appreciated.
