### ISSUE TITLE
Problematic non-strict-security mode implemention

### ISSUE THREAD

**Issue by wfjsw** [warlof/seat-discord-connector#59]
Current implemention gives user role regardless whether refresh token is valid. This differs from original implemention, which only give role based on each valid token.

**Comment by warlof** [comment]
wasn't the purpose of your PR https://github.com/warlof/seat-discord-connector/pull/47/files ?

**Comment by wfjsw** [comment]
Pay attention to

https://github.com/warlof/seat-discord-connector/pull/47/files#diff-117375df1570a3c7d1ab459aed7d0d7bL116-R119 

https://github.com/warlof/seat-discord-connector/pull/47/files#diff-117375df1570a3c7d1ab459aed7d0d7bL126-R129

https://github.com/warlof/seat-discord-connector/pull/47/files#diff-117375df1570a3c7d1ab459aed7d0d7bL126-R129

When calculating permissions, only active tokens are taken into account.

**Comment by warlof** [comment]
I got it
It's indead not expected.
