### ISSUE TITLE
Fatal error when SeAT users do not have a main character selected.

### ISSUE THREAD

**Issue by KingVoodoo** [warlof/seat-discord-connector#6]
In SeatGroupsUserUpdate.php line 40:

  Trying to get property of non-object

Given this fatal error when Users don't have a main character set. Stops all other users from being assigned Seat Roles

**Comment by warlof** [comment]
are you coming from beta version of SeAT ?

**Comment by warlof** [comment]
Closing this issue as it's not related with that package.
