### ISSUE TITLE
MemberOrchestrator doing nothing with User Filters, just succesfully running? 

### ISSUE THREAD

**Issue by porowns** [warlof/seat-discord-connector#61]
Added a few user filters for my Discord user, nothing seems to be happening... no logs, MemberOrchestrator just successfully runs. 

Would expect User Filter to be adding the group set to the Discord user... and displaying errors if it was broken?

**Comment by porowns** [comment]
Finally got it to start failing... No error message just:
```
{
  "tags": [
    "orchestrator"
  ],
  "client": null,
  "guild": null,
  "members": null,
  "roles": null,
  "terminator": false,
  "tries": 100,
  "job": null,
  "connection": null,
  "queue": "high",
  "chainConnection": null,
  "chainQueue": null,
  "delay": null,
  "chained": []
}
```

**Comment by warlof** [comment]
@porowns do you have any linked user ?
`Discord` > `User Mapping` will show you them

**Comment by porowns** [comment]
Yes, I have my Discord ID there:

SeAT Group ID | SeAT User ID | SeAT Username | Discord ID | Discord Display Name |  
-- | -- | -- | -- | -- | --
4 | 2115515875 | Developer Throwaway | 124039469488799746 | BearThatCares

**Comment by warlof** [comment]
Are you administrator or the the owner ?

**Comment by porowns** [comment]
Administrator

**Comment by warlof** [comment]
So that's the reason. Bot will not touch admin or owner due to api access restrictions.
