### ISSUE TITLE
[Feature Request] Nickname setting

### ISSUE THREAD

**Issue by aaronmallen** [warlof/seat-discord-connector#7]
It would be awesome if you could implement a setting, can be opt-in, that would update the discord user with a nickname `[CORP_TICKER] EVE_CHARACTER_NAME`, bonus points if the format is configurable.

**Comment by paulipa** [comment]
+1 for corp ticker

**Comment by H4Z4RD-H42** [comment]
Please give us the possibility to change discord username to eve username.

**Comment by paulipa** [comment]
> 
> 
> Please give us the possibility to change discord username to eve username.

If by eve username you mean the username they log in with on SSO thats not possible as that is not revealed for security reasons. If you mean ingame name for main character, the program already does that. Make sure your cronjobs are running.

**Comment by H4Z4RD-H42** [comment]
> > Please give us the possibility to change discord username to eve username.
> 
> If by eve username you mean the username they log in with on SSO thats not possible as that is not revealed for security reasons. If you mean ingame name for main character, the program already does that. Make sure your cronjobs are running.

@paulipa 
Mmhh... which is?
I have discord:user:policy and discord:role:sync running. The only one that not running is discord:user:terminator but I think it's not it.
