### ISSUE TITLE
Discord Connector dropping roles for a few minutes occasionally

### ISSUE THREAD

**Issue by aaronmallen** [warlof/seat-discord-connector#9]
I've noticed that discord will drop some roles on some users for a few minutes fairly randomly... not sure how to reproduce this. I have seatgroups updating user roles so Im not sure if this is a you issue or an issue with @herpaderpaldent.  What is weird is it never seems to drop roles that are managed by `auto` seatGroups.

Cron info:
```
discord:user:policy `*,30 * * * *`
discord:role:sync `0 * * * *`
seat-groups:users:update `* * * * *`
```

Filters:

Role | Discord Role | Created | Updated At | Status |  
-- | -- | -- | -- | -- | --
Member | Member | 2018-06-23 07:24:02 | 2018-06-23 07:24:02 |   | Remove
Admin | Admin | 2018-06-23 07:22:10 | 2018-06-23 07:22:10 |   | Remove
CEO/Director | CEO/Director | 2018-06-23 07:22:40 | 2018-06-23 07:22:40 |   | Remove
Leadership | Leadership | 2018-06-23 07:23:24 | 2018-06-23 07:23:24 |   | Remove
FC | FC | 2018-06-23 07:23:08 | 2018-06-23 07:23:08 |   | Remove
Skirmish FC | Skirmish FC | 2018-06-23 07:24:31 | 2018-06-23 07:24:31 |   | Remove
Recuriter | Recruiter | 2018-06-23 07:24:20 | 2018-06-23 07:24:20 |   | Remove
Accountant | Accountant | 2018-06-23 07:21:55 | 2018-06-23 07:21:55 |   | Remove
Supers | Supers | 2018-06-23 07:24:52 | 2018-06-23 07:24:52 |   | Remove
Capitals | Capitals | 2018-06-23 07:22:30 | 2018-06-23 07:22:30 |   | Remove
Logistics | Logistics | 2018-06-23 07:23:49 | 2018-06-23 07:23:49 |   | Remove
Corp [FE1GN] Feign-Disorder | [FE1GN] Feign Disorder | 2018-06-23 07:21:25 | 2018-06-23 07:21:25 |   | Remove
Corp [FE1GN] Feign-Disorder Leadership | [FE1GN] Leadership | 2018-06-23 21:16:23 | 2018-06-23 21:16:23 |   | Remove
Corp [OP.6S] Disturbance. | [OP.6S] Disturbance | 2018-06-23 07:21:42 | 2018-06-23 07:21:42 |   | Remove
Corp [OP.6S] Disturbance. Leadership | [OP.6S] Leadership | 2018-06-23 21:16:48 | 2018-06-23 21:16:48 |   | Remove
Corp [.HOM.] Hand Of Midas | [.HOM.] Hand Of Midas | 2018-06-23 07:21:06 | 2018-06-23 07:21:06 |   | Remove
Corp [.HOM.] Hand Of Midas Leadership | [.HOM.] Leadership | 2018-06-23 21:17:05 | 2018-06-23 21:17:05 |   | Remove
DiscordChannelPolitics | Politics | 2018-06-23 20:28:57 | 2018-06-23 20:28:57 |   | Remove
DiscordChannelMemes | Memer | 2018-06-23 20:29:09 | 2018-06-23 20:29:09 |   | Remove
DiscordRoleFriends | Friends | 2018-06-24 17:45:41 | 2018-06-24 17:45:41 |   | Remove

**Comment by herpaderpaldent** [comment]
@warlof had reviewed my code and i don't think this is caused by my plugin. Mainly because seat-groups does not remove roles before assigning them back again. Only the delta between _is_ and _should_ is processed. (With Laravels Eloquent Sync)

**Comment by warlof** [comment]
@aaronmallen you forget to put the filter type which could be usefull too.
About dropped roles randomly; do you see if it's happening for specific filter type or all of them ?
Are they dropped on same users all the time ?

**Comment by aaronmallen** [comment]
I only use role filters atm. I have noticed it seems to target the same-ish users a few times but I'm not 100% on that. I know of one user it's dropped the same roles for 2 or 3 times.

**Comment by warlof** [comment]
Thank you for those extra information.
I'll double check during the week.

**Comment by warlof** [comment]
@aaronmallen is it still the case since last update?

**Comment by aaronmallen** [comment]
I literally have not seen it happen since I swapped discord servers
